### ISSUE TITLE
Priority banners

### ISSUE THREAD

**Issue by barrucadu** [lainchan/lainchan#57]
It might be nice to be able to have "priority" banners which show up more frequently.

## Tasks:

- [ ] Add a second banner directory (for priority banners).
- [ ] Make b.php pick from the priority banners with a fixed chance (rather than random selection across ALL banners).
- [ ] List priority banners in banners.php
